CREATE TABLE IF NOT EXISTS apps_scopes(
  app_id INT NOT NULL,
  scope_id INT NOT NULL,
  PRIMARY KEY (app_id, scope_id),
  FOREIGN KEY (app_id) REFERENCES apps(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (scope_id) REFERENCES scopes(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
