CREATE TABLE IF NOT EXISTS apps(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(25) NOT NULL,
  user_id INT NOT NULL,
  deleted_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
