CREATE TABLE IF NOT EXISTS clients(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(25) NOT NULL,
  secret VARCHAR(50) NOT NULL,
  label VARCHAR(64) NOT NULL,
  user_id INT NOT NULL,
  deleted_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX (name),
  UNIQUE INDEX (secret),
  FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
