CREATE TABLE IF NOT EXISTS scopes(
  id INT NOT NULL AUTO_INCREMENT,
  scope VARCHAR(255) NOT NULL,
  deleted_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
